workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: 3.29.0
    triggering:
      events:
        - push
    script: |
      echo "Building Android Release"
      flutter clean
      flutter pub get
    publishing:
      email:
        recipients:
          - christianlloyd.b.salon@gmail.com
