workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      groups:
        - firebase
        - files
      flutter: 3.29.0
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up Environment
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          flutter clean
          flutter pub get
          chmod +x scripts/create-fastlane-env.sh
          chmod +x scripts/create-env.sh
          ./scripts/create-fastlane-env.sh
          ./scripts/create-env.sh
          $FLUTTER_ROOT/bin/dart env.dart
          echo "Created env.dart"

      - name: Pre-build Scripts
        script: |
          ls -la $FCI_BUILD_DIR
          echo ${GOOGLE_SERVICES_JSON} | base64 --decode > $FCI_BUILD_DIR/android/app/google-services.json
          echo ${JKS_FILE} | base64 --decode > $FCI_BUILD_DIR/android/app/release_keystore.jks
          echo ${KEYSTORE_PROPERTIES} | base64 --decode > $FCI_BUILD_DIR/android/key.properties

      - name: Android Release Fastlane
        script: |
          gem install bundler:1.17.2
          cd android
          bundle install
          bundle exec fastlane android build
          bundle exec fastlane android release

    publishing:
      email:
        recipients:
          - christianlloyd.b.salon@gmail.com
